[refactor]:

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # https://asdf-vm.com/plugins/create.html#bin-download
-# # Download a specified version
+# # Download a specified ASDF_INSTALL_VERSION
 # must download to ASDF_DOWNLOAD_PATH
 # on failure, clean download path
 
@@ -20,6 +20,13 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 source "${plugin_dir}/lib/utils.bash"
 
 release_file="$TOOL_NAME-$ASDF_INSTALL_VERSION.jar"
+url="$GH_REPO/releases/download/v${ASDF_INSTALL_VERSION}/${release_file}"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+mkdir -p "$ASDF_DOWNLOAD_PATH"
+
+echo "* Downloading $TOOL_NAME release $version..."
+echo "* To: $ASDF_DOWNLOAD_PATH/$release_file"
+curl "${curl_opts[@]}" -o "$ASDF_DOWNLOAD_PATH/${TOOL_NAME}.jar" -C - "$url" || fail "Could not download $url"
+
+test -f "$ASDF_DOWNLOAD_PATH/${TOOL_NAME}.jar" || fail "expected download file did not download"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,4 +13,31 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+exec_script="#!/usr/bin/env bash
+set -euo pipefail
+
+if [[ \$# -eq 0 ]]; then
+       java -jar ${TOOL_NAME}.jar -help
+else
+       java -jar ${TOOL_NAME}.jar \"\$@\"
+fi"
+
+echo "* Installing to: $ASDF_INSTALL_PATH"
+[[ "$ASDF_INSTALL_TYPE" != "version" ]] || fail "asdf-$TOOL_NAME supports release installs only"
+
+(
+    mkdir -p "$ASDF_INSTALL_PATH/bin"
+    cp -r "$ASDF_DOWNLOAD_PATH/${TOOL_NAME}.jar" "$ASDF_INSTALL_PATH/bin/"
+
+    echo "* Creating Run Script"
+    echo "$exec_script" > "$ASDF_INSTALL_PATH/bin/${TOOL_NAME}"
+    chmod  +x "ASDF_INSTALL_PATH/bin/${TOOL_NAME}"
+
+    tool_cmd="$(echo "$TOOL_TEST" | cut -d' ' -f1)"
+    "$ASDF_INSTALL_PATH/bin/${TOOL_NAME}" -version || fail "Expected $ASDF_INSTALL_PATH/bin/$tool_cmd to be executable."
+
+    echo "* $TOOL_NAME $ASDF_INSTALL_VERSION installation was successful!"
+) || (
+    rm -rf "$ASDF_INSTALL_PATH"
+    fail "An error occurred while installing $TOOL_NAME $ASDF_INSTALL_VERSION."
+)
